= Simple Stock App

This is a simple project which simulate a buy and sell a stock.
The main purpose is to simulate a transactional process with high throughput.

* Using `@Transactional` annotation
* `Optimistic Locking` was chosen by adding `@Version` annotation in the entity class
* Using simple lock mechanism of `@Lock(LockModeType.PESSIMISTIC_WRITE)` in order to acquire an exclusive lock on the database row to prevent other transactions from reading or writing to it.
- Using `PESSIMISTIC_WRITE` ensures that once a transaction reads the user's data for update, no other transaction can modify it until the first one commits.
* Having pagination for fetching all user trades
* Connection Pool was enabled by default using HikariCP

[#_tech_stack]
=== Tech Stack

* Spring Boot (3.4.3)
* Java (21)
* Postgres DB
* Docker
* K6 (Load Testing)

[#_how_to_use]
=== How to Use

* Run the docker-compose to spin up a Postgres DB
* Run the spring boot project (automatically trigger the data initializer)
* Install k6 locally to run API test script (https://grafana.com/docs/k6/latest/set-up/install-k6/[Reference])

[#_performance]
=== Performance

In order to measure the API performance, we will use k6.
There are 2 types of test to perform :

* constant rate request (default)
* ramped-up rate request (update the `script.js`)

To run the test, you need to run command :
[source,bash]
----
k6 run script.js
----

If you prefer web based report, you can run command :
[source,shell]
----
K6_WEB_DASHBOARD=true K6_WEB_DASHBOARD_EXPORT=[report_file_name].html k6 run script.js
----

[#_todos]
=== TODOs:

* [ ] Implement proper exception handling
* [x] Implement k6 script which use `ramping-arrival-rate`
* [ ] Implement retry mechanism
* [ ] Perform the test on VPS